inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/**/*'
    - 'config/puma.rb'
    - 'config.ru'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

RSpec/Rails/InferredSpecType:
  Enabled: false

# 特に model 内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

# 使用しているAPIの使用的に厳しい気がするので少し緩める
Metrics/AbcSize:
  Max: 18
