databases:
  - name: Invest_app_db
    databaseName: invest_app_production
    user: invest_app

services:
  - type: web
    name: Invest_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Invest_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
