databases:
  - name: Invest_app_db
    databaseName: invest_app_production
    user: invest_app

services:
  - type: web
    name: Invest_app
    env: ruby
    region: singapore
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Invest_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: cron
    name: Invest_app_cron_stock_prices_update_jp
    env: ruby
    plan: starter
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rake stock_prices:update_jp
    schedule: 0 0,1,2,3,4,5,6,7 * * 1-5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Invest_app_db
          property: connectionString

  - type: cron
    name: Invest_app_cron_stock_prices_update_us
    env: ruby
    plan: starter
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rake stock_prices:update_us
    schedule: 30 13,14,15,16,17,18,19,20,21 * * 1-5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Invest_app_db
          property: connectionString

  - type: cron
    name: Invest_app_cron_calculate_user_asset
    env: ruby
    plan: starter
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rake user:calculate_total_asset
    schedule: 0 13 * * 1-5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Invest_app_db
          property: connectionString
